# /etc/security/limits.conf
#
#This file describes the limits that are placed on each login.
#See the limits.conf man page for more information.
#

*               -       rtprio     99
*               -       nice       -20